# Port & Project-Name Configuration
server:
  port: 7071
  servlet:
    context-path: /pmp


# DataSource Configuration
spring:
  profiles:
    active: dev
  redis:
    host: localhost
logging:
  level:
    com:
      wyhw:
        pmp: debug
