spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${config.mysql.server}:3306/pmp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: ${config.mysql.name}
    password: ${config.mysql.password}
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
config:
  mysql:
#    server: 192.168.163.129
    server: 127.0.0.1
    name: root
#    password: 123456
    password: root

