# Port & Project-Name Configuration
server:
  port: 8080
  servlet:
    context-path: /pmp


# DataSource Configuration
spring:
  profiles:
    active: dev
  redis:
    host: localhost
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: false
    pool:
      enabled: true
      max-connections: 10
      idle-timeout: 30000

queue-name: Queue-Demo

logging:
  level:
    com: debug

nacos:
  config:
    server-addr: 192.168.163.128:8848

dubbo:
  application:
    name: nacos-pmp
  registry:
    address: nacos://${nacos.config.server-addr}
  scan:
    base-packages: com.wyhw.pmp.service.impl
  protocol:
    port: 20882
    name: dubbo