# Port & Project-Name Configuration
server:
  port: 7071
  servlet:
    context-path: /pmp


# DataSource Configuration
spring:
  profiles:
    active: dev
  redis:
    host: localhost
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: false
    pool:
      enabled: true
      max-connections: 10
      idle-timeout: 30000

queue-name: Queue-Demo

logging:
  level:
    com:
      wyhw:
        pmp: debug
